### ISSUE TITLE
Audio Dataset

### ISSUE THREAD

**Issue by will-rice** [vjjan91/acoustics-westernGhats#7]
I would like to use the dataset if possible. Is it published online?

**Comment by vjjan91** [comment]
Hope you found our paper!

The dataset is published and available to use alongside the paper. You can download it from the data folder if you need to!

Please be sure to cite this work:

Ramesh, V., Hariharan, P., Akshay, V. A., Choksi, P., Khanwilkar, S., DeFries, R., & Robin, V. V. (2023). Using passive acoustic monitoring to examine the impacts of ecological restoration on faunal biodiversity in the Western Ghats. Biological Conservation, 282, 110071.
